# Generated by Django 2.1 on 2018-10-18 07:17

from django.db import migrations, models
import orm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('posted_at', models.DateField()),
            ],
            managers=[
                ('objects', orm.models.PostManager()),
            ],
        ),
    ]
